<?php include __DIR__ . '/../layout/header.php'; ?>
<!-- Inject CSRF token for JS -->
<script>
    window.CSRF_TOKEN = '<?= e(csrf_token()) ?>';
</script>

<div class="row">
  <div class="col-lg-9">
    <div class="card">
      <div class="card-header">
        Editor de Sección <?= !empty($section) ? '- ' . e($section['title']) : '' ?>
      </div>
      <div class="card-body">
        <?php if (!empty($section)): ?>
          <form id="form-editor">
            <!-- Hidden inputs for JS to grab -->
            <input type="hidden" name="section_id" value="<?= (int)$section['id'] ?>">
            
            <div class="mb-3">
              <label class="form-label">Contenido</label>
              <!-- Textarea ID verified as #contenido for CKEditor -->
              <textarea class="form-control" id="contenido" name="content" rows="10"><?= e($section['content'] ?? '') ?></textarea>
            </div>
            <div class="d-flex gap-2">
              <button class="btn btn-secondary" type="button" data-action="guardar">Guardar borrador</button>
              <button class="btn btn-success" type="button" data-action="completar">Marcar como completado</button>
              <button class="btn btn-warning" type="button" data-action="revision">Solicitar revisión</button>
            </div>
          </form>
        <?php else: ?>
          <div class="alert alert-info">Selecciona una sección desde tu panel para editar.</div>
        <?php endif; ?>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="card">
      <div class="card-header">Historial</div>
      <div class="card-body" id="historial">
          <!-- Populated by JS -->
          <div class="text-muted small">Cargando...</div>
      </div>
    </div>
  </div>
</div>

<!-- Scripts -->
<script type="module">
    // Adjust paths: app_url() might be needed if JS modules are strictly located.
    // For now assuming we can load them via relative path from public root or absolute.
    // Since this is rendered at /editor uri, relative paths like './assets' might fail if not carefully handled.
    // We'll use absolute paths generated by PHP for robustness.
    
    // Note: The original code used relative paths '../assets/js/...'. 
    // Since we are now in the Front Controller at /public/index.php (or re-written), 
    // the browser sees URL /editor or /informe/editor. 
    // So 'assets/js' is at '/informe/public/assets/js'.
    
    import { initEditor } from '<?= app_url('assets/js/editor.js') ?>';
    import { apiFetch } from '<?= app_url('assets/js/api.js') ?>';
    import { showToast } from '<?= app_url('assets/js/main.js') ?>';

    // Initialize CKEditor
    initEditor('#contenido');

    const form = document.getElementById('form-editor');
    if (form) {
      form.addEventListener('click', async (e) => {
        const btn = e.target.closest('button[data-action]');
        if (!btn) return;
        e.preventDefault(); // Stop form submission if button type=submit, though we changed to type=button
        
        const action = btn.dataset.action;
        const contenidoEl = document.querySelector('#contenido');
        
        // CKEditor 5 stores instance on element or we need a reference. 
        // Original code assumed `contenidoEl.__ckInstance`. We'll hope editor.js attaches it there.
        const ck = contenidoEl && contenidoEl.__ckInstance;
        const contentValue = ck ? ck.getData() : (contenidoEl ? contenidoEl.value : '');
        
        const payload = {
            section_id: Number(form.section_id.value),
            content: contentValue || '',
            _csrf_token: window.CSRF_TOKEN
        };
        
        // API Endpoints - mapped to legacy API for now till we refactor API
        // Legacy: ../api/contribuciones.php
        // New: app_url('api/contribuciones.php')
        let endpoint = '';
        const apiBase = '<?= app_url('api/contribuciones.php') ?>';
        
        if (action === 'guardar') endpoint = apiBase + '?action=guardar';
        if (action === 'completar') endpoint = apiBase + '?action=completar';
        if (action === 'revision') endpoint = apiBase + '?action=solicitar_revision';
        
        try {
            const res = await apiFetch(endpoint, { method: 'POST', body: JSON.stringify(payload) });
            showToast(res.message || 'Acción realizada', 'success');
            loadHistorial();
        } catch (err) {
            console.error(err);
            showToast(err.message || 'Error de conexión', 'danger');
        }
      });

      async function loadHistorial() {
        try {
            const apiBase = '<?= app_url('api/contribuciones.php') ?>';
            const res = await apiFetch(apiBase + '?action=historial&section_id=' + Number(form.section_id.value));
            const cont = document.getElementById('historial');
            cont.innerHTML = (res.items || []).map(h => 
                `<div class="small border-start ps-2 mb-2">
                    <b>${h.action}</b> - ${h.created_at}<br>
                    ${h.comment ? h.comment : ''}
                </div>`
            ).join('') || '<em>Sin cambios</em>';
        } catch (e) {
            console.error('History load failed', e);
        }
      }
      // Load history on start
      loadHistorial();
    }
</script>

<?php include __DIR__ . '/../layout/footer.php'; ?>
